### ISSUE TITLE
Online examples

### ISSUE THREAD

**Issue by suhr** [mlajtos/L1#1]
To learn the language by examples.

**Comment by mlajtos** [comment]
There is the [built-in documentation](https://mlajtos.github.io/L1/latest/#OjpTZWxm) that lets you run attached code examples. 

Or are you suggesting something else?

**Comment by suhr** [comment]
Oh, cool! This is not very discoverable though.

But I mean example programs. Like [here](https://swish.swi-prolog.org/) or [here](https://try.kotlinlang.org).

**Comment by mlajtos** [comment]
The big part of differentiable linear algebra is the optimization, which is the main point of this project. In [one example](https://github.com/mlajtos/L1/blob/master/src/gallery/23_regress_tensor.l1), you can see how you might write one. (Please excuse personal notes.) And [on the video](https://youtu.be/6H4CyboPIXE) you can see how the process might look like.

I didn’t make these examples public as they are old (from before rewrite of the interpreter), so I would only confuse people more than they probably are. :)

Some of the examples (even without the optimization) are really surprising for me and I would like some explanations, but that won’t happen until I fix the missing parts.

More explicit examples are definitely coming, I just need some time to get all the details right.

**Comment by mlajtos** [comment]
I reworked the list of [working examples](https://github.com/mlajtos/L1/tree/master/src/gallery). They point directly to the playground, so one can see what they are doing right away.

**Comment by mlajtos** [comment]
The infrastructure for providing examples is there. It is crude, but working. The examples will come as I further develop the playground. I would like to provide some tutorial in form of [Koans](http://clojurescriptkoans.com/), but for now this is sufficient.
