### ISSUE TITLE
Fold (reduce)?

### ISSUE THREAD

**Issue by suhr** [mlajtos/L1#4]
I just wanted to do `{+/ ⍵*2}`...

**Comment by mlajtos** [comment]
This is something I would love to support **the right way**, but I am afraid it won't happen. But there will be a `+/` operator for `Sum` and `*/` for `Product`.

I have really no idea how to support generalized reductions. :(

4666e218c888f490d111238f198695fbe203ced2

**Comment by suhr** [comment]
Well, that's unfortunate. But what's the problem with generalized reductions?

**Comment by mlajtos** [comment]
Ok, I might have been quick to judge.

So far, the only problem right now is that scan is not supported by the TF.js. When it will be available, it should not be a problem to implement it.

**Comment by mlajtos** [comment]
Until tf.scan is available, there will be fake “+/“ and “*/” and then I will revisit the reductions in a proper way. So closing for now...

**Comment by mlajtos** [comment]
[::Sum](https://mlajtos.github.io/L1/latest/#OjpTdW0=) – introduced in be02a2e5cb21353716ec632b07d2e6f9ae856859

I lied. Sum is an unary `+`, not `+/`. Same will go for a Product as unary `*`.

(Originally, I intended unary `*` as an operator for Sign function, but this is much better.)

**Comment by mlajtos** [comment]
I read my comment again, and I realized I mixed up reduction and scan... Anyway, I like the idea of sum as an unary `+`. As for cumsum (`+\`) I have no idea what would be a good notation, or how to support tf.scan in the future.
