### ISSUE TITLE
Don't hide results on an error

### ISSUE THREAD

**Issue by suhr** [mlajtos/L1#5]
This is distracting. Also, you usually want to see previous results while writing the code.

**Comment by mlajtos** [comment]
Yes, this is a valid point – stability of visualization is necessary (learned that one [here](https://www.youtube.com/watch?v=0DC0RMnuwxU)).

There is a specific thing to be aware of. Writing the following char-by-char:
1.
```L1
a: 3
```
2.
```L1
a: 3
b
```
3.
```L1
a: 3
b:
```
4.
```L1
a: 3
b: 4
```
---
In step 2. the code is interpreted as `a: 3 b` (calling 3 as a function on non-existing prop). 3. step is syntax error, and finally 4. step is a valid and intended code. So the last syntactically valid code is semantically wrong – step 2. This can be really confusing. However, it can be mitigated by using commas as separators.

This should be trivial to implement.

**Comment by mlajtos** [comment]
Ok, it is much better now. Thank you for the push. :)
